# Generated by Django 3.1 on 2021-04-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210416_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='categorys',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(default='ram', on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to='auctions.user'),
            preserve_default=False,
        ),
    ]
