# Generated by Django 3.1 on 2021-04-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210415_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='photo',
            field=models.ImageField(height_field=400, upload_to='commerce/auction/photo/', width_field=300),
        ),
    ]
