# Generated by Django 3.1 on 2021-04-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210415_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
