# Generated by Django 3.1 on 2021-04-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com',
            field=models.TextField(),
        ),
    ]
