# Generated by Django 3.1 on 2021-04-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210415_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='photo',
            field=models.ImageField(height_field=200, upload_to='image/', width_field=200),
        ),
    ]
