# Generated by Django 3.1 on 2021-04-15 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210415_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('BOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_product', to='auctions.auction_listing')),
                ('user', models.ManyToManyField(blank=True, related_name='bidder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
