# Generated by Django 3.1 on 2021-04-15 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='number',
            new_name='amount',
        ),
    ]
