# Generated by Django 3.1 on 2021-04-15 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210415_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.CharField(max_length=526)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentOnProduct', to='auctions.auction_listing')),
            ],
        ),
    ]
