# Generated by Django 3.1 on 2021-04-16 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210415_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='categorys',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
