# Generated by Django 3.1 on 2021-04-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auction_listing_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='categorys',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
