# Generated by Django 3.1 on 2021-04-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210416_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='user',
        ),
    ]
